/// Generated by AssetsRefGenerator on 2022/04/20
class Res {
  static const String back = "assets/back.png";
  static const String front = "assets/front.png";
  static const String Sansserif = "assets/fonts/Sansserif.ttf";
  static const String workout = "assets/workout.jpg";
}
